"use client"
import { QueryClient, QueryClientProvider } from 'react-query';
import './globals.css'
import { Inter } from 'next/font/google'

import { Provider } from "react-redux";
import { store } from './store/store';
const inter = Inter({ subsets: ['latin'] })
const queryClient = new QueryClient();

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Provider store={store}>
        <QueryClientProvider client={queryClient}>
          <body className={inter.className}>{children}</body>
        </QueryClientProvider>
      </Provider>
    </html>
  )
}
